version: '3'

networks:
  app-tier:
    driver: bridge

services:
  api-movie:
    build: .
    networks:
      - app-tier
    ports:
      - "8050:8050"
    depends_on:
      - dbpgsql
    volumes:
      - ".:/api-movie/src/app/"
  dbpgsql: # Host DB
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - app-tier